In [1]:
import pandas as pd
from numpy import set_printoptions
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression
from sklearn.tree import  DecisionTreeClassifier
import warnings
warnings.filterwarnings("ignore")

## Univariate Feature Selection

Feature Extraction with Univariate Statistical Tests (Chi-squared for classification)     
For regression: f_regression, mutual_info_regression                              
For classification: chi2, f_classif, mutual_info_classif

In [2]:
names = ['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']
df = pd.read_csv("/11.pima-indians-diabetes.csv",names=names)
df.head()

preg  plas  pres  skin  test  mass   pedi  age  class
0     6   148    72    35     0  33.6  0.627   50      1
1     1    85    66    29     0  26.6  0.351   31      0
2     8   183    64     0     0  23.3  0.672   32      1
3     1    89    66    23    94  28.1  0.167   21      0
4     0   137    40    35   168  43.1  2.288   33      1

In [3]:
array = df.values
X = array[:,0:8]
Y = array[:,8]

In [4]:
# feature extraction
test = SelectKBest(chi2, k=4) # k=k no. of best features
fit = test.fit(X, Y)

In [5]:
# summarize scores
set_printoptions(precision=3)
print(fit.scores_)
features = fit.transform(X)

[ 111.52  1411.887   17.605   53.108 2175.565  127.669    5.393  181.304]


Highest score is more contributing feature

##  Recursive Feature Elimination

In [6]:
# feature extraction
model = LogisticRegression(max_iter=500)
rfe = RFE(model, 4)
fit = rfe.fit(X, Y)

In [7]:
#Num Features: 
fit.n_features_

4

In [8]:
#Selected Features: which feature is contributing towards target variable
fit.support_

array([ True,  True, False, False, False,  True,  True, False])

In [9]:
# Feature Ranking:
fit.ranking_

array([1, 1, 3, 5, 4, 1, 1, 2])

## Feature Importance using Decision Tree

In [10]:
# feature extraction
model = DecisionTreeClassifier()
model.fit(X, Y)
print(model.feature_importances_)

[0.057 0.318 0.101 0.012 0.032 0.229 0.135 0.115]
